---
# Global fabric settings
fabric_name: multi-dc-evpn
management_subnet: 172.20.20.0/24

# Connection settings for all devices
ansible_connection: network_cli
ansible_network_os: arista.eos.eos
ansible_user: admin
ansible_password: admin
ansible_become_method: enable
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
