---
device_name: dc1-spine2
loopback0_ip: 10.0.0.2/32
bgp_asn: 65000

spine_interfaces:
  - name: Ethernet1
    remote_device: dc1-leaf1
    remote_interface: Ethernet2
    p2p_ip: 10.1.1.0/31
    bgp_asn: 65101
  - name: Ethernet2
    remote_device: dc1-leaf2
    remote_interface: Ethernet2
    p2p_ip: 10.1.1.2/31
    bgp_asn: 65102
  - name: Ethernet3
    remote_device: dc1-leaf3
    remote_interface: Ethernet2
    p2p_ip: 10.1.1.4/31
    bgp_asn: 65103
  - name: Ethernet4
    remote_device: dc1-leaf4
    remote_interface: Ethernet2
    p2p_ip: 10.1.1.6/31
    bgp_asn: 65104

inter_dc_interfaces:
  - name: Ethernet5
    remote_device: dc2-spine1
    remote_interface: Ethernet6
    p2p_ip: 10.3.0.4/31
    bgp_asn: 65001
  - name: Ethernet6
    remote_device: dc2-spine2
    remote_interface: Ethernet6
    p2p_ip: 10.3.0.6/31
    bgp_asn: 65001
