---
device_name: dc2-spine1
loopback0_ip: 10.0.1.1/32
bgp_asn: 65001

spine_interfaces:
  - name: Ethernet1
    remote_device: dc2-leaf1
    remote_interface: Ethernet1
    p2p_ip: 10.2.0.0/31
    bgp_asn: 65201
  - name: Ethernet2
    remote_device: dc2-leaf2
    remote_interface: Ethernet1
    p2p_ip: 10.2.0.2/31
    bgp_asn: 65202
  - name: Ethernet3
    remote_device: dc2-leaf3
    remote_interface: Ethernet1
    p2p_ip: 10.2.0.4/31
    bgp_asn: 65203
  - name: Ethernet4
    remote_device: dc2-leaf4
    remote_interface: Ethernet1
    p2p_ip: 10.2.0.6/31
    bgp_asn: 65204

inter_dc_interfaces:
  - name: Ethernet5
    remote_device: dc1-spine1
    remote_interface: Ethernet5
    p2p_ip: 10.3.0.1/31
    bgp_asn: 65000
  - name: Ethernet6
    remote_device: dc1-spine2
    remote_interface: Ethernet5
    p2p_ip: 10.3.0.5/31
    bgp_asn: 65000
